version: '3'

tasks:
  build:
    desc: "Build the wefthcl package"
    cmds:
      - go build ./...

  test:
    desc: "Run tests for the wefthcl package"
    cmds:
      - go test ./...

  lint:
    desc: "Vet the wefthcl package"
    cmds:
      - go vet ./...